import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Login/Auth
    'auth.title': 'RestaurantOS',
    'auth.subtitle': 'Professional Restaurant Management',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.createAccount': 'Create Account',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.role': 'Role',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password (min 6 characters)',
    'auth.language': 'Language',
    'auth.demoAccounts': 'Demo accounts (create new ones or use these for testing):',
    'auth.loading': 'Loading RestaurantOS',
    'auth.settingUp': 'Setting up your restaurant management system...',
    
    // Roles
    'role.customer': 'Customer',
    'role.waiter': 'Waiter',
    'role.kitchen': 'Kitchen Staff',
    'role.manager': 'Manager',
    
    // Categories
    'category.Food': 'Food',
    'category.Drink': 'Drink',
    'category.Dessert': 'Dessert',
    'category.Appetizer': 'Appetizer',
    'category.Main Course': 'Main Course',
    'category.Side Dish': 'Side Dish',
    'category.Beverage': 'Beverage',
    'category.Alcohol': 'Alcohol',
    'category.Coffee': 'Coffee',
    'category.Tea': 'Tea',
    'category.Salads': 'Salads',
    'category.Desserts': 'Desserts',
    'category.Beverages': 'Beverages',
    
    // Common
    'common.welcome': 'Welcome',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.refresh': 'Refresh',
    'common.logout': 'Logout',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.total': 'Total',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.status': 'Status',
    'common.notes': 'Notes',
    'common.optional': 'optional',
    'common.details': 'Details',
    'common.legend': 'Legend',
    'common.howToUse': 'How to use',
    'common.clickToView': 'Click to view',
    'common.clickToEdit': 'Click to edit',
    'common.clickToOrder': 'Click to order for this seat',
    'common.viewAll': 'View All',
    'common.tryAgain': 'Try Again',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.category': 'Category',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.customer': 'Customer',
    'common.table': 'Table',
    'common.time': 'Time',
    'common.date': 'Date',
    'common.items': 'Items',
    'common.guest': 'Guest',
    
    // Navigation - Desktop
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.menu': 'Menu',
    'nav.tables': 'Tables',
    'nav.reports': 'Reports',
    'nav.staff': 'Staff',
    'nav.ai': 'AI Assistant',
    'nav.ordersOverview': 'Orders Overview',
    'nav.menuManagement': 'Menu Management',
    'nav.takeOrder': 'Take Order',
    'nav.quickOrder': 'Quick Order',
    'nav.tableView': 'Table View',
    'nav.staffOverview': 'Staff Overview',
    'nav.salesReports': 'Sales Reports',
    'nav.pendingOrders': 'Pending Orders',
    'nav.inventoryView': 'Inventory View',
    'nav.cartCheckout': 'Cart/Checkout',
    'nav.aiAgent': 'AI Agent',
    'nav.myOrders': 'My Orders',
    'nav.browseMenu': 'Browse Menu',
    'nav.drinkOrders': 'Drink Orders',
    'nav.barInventory': 'Bar Inventory',
    'nav.barMenu': 'Bar Menu',
    
    // Navigation - Mobile (shorter labels)
    'nav.order': 'Order',
    'nav.pending': 'Pending',
    'nav.done': 'Done',
    'nav.stock': 'Stock',
    'nav.cart': 'Cart',
    'nav.quick': 'Quick',
    'nav.drinks': 'Drinks',
    
    // Dashboard
    'dashboard.welcome': 'Welcome Back',
    'dashboard.todaysSpecial': "Today's Special",
    'dashboard.orderNow': 'Order Now',
    'dashboard.browseMenu': 'Browse Menu',
    'dashboard.quickOrder': 'Quick Order',
    'dashboard.reviews': 'Reviews',
    'dashboard.favorites': 'Favorites',
    'dashboard.featuredItems': 'Featured Items',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.noOrders': "You haven't placed any orders yet",
    'dashboard.managerDashboard': 'Manager Dashboard',
    'dashboard.waiterDashboard': 'Waiter Dashboard',
    'dashboard.kitchenDashboard': 'Kitchen Dashboard',
    'dashboard.customerDashboard': 'Customer Dashboard',
    'dashboard.todaysRevenue': "Today's Revenue",
    'dashboard.ordersToday': 'Orders Today',
    'dashboard.activeStaff': 'Active Staff',
    'dashboard.avgOrderTime': 'Avg Order Time',
    'dashboard.salesTrend': 'Sales Trend',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.completedToday': 'Completed Today',
    'dashboard.avgPrepTime': 'Avg Prep Time',
    'dashboard.lowStockItems': 'Low Stock Items',
    'dashboard.orderQueue': 'Order Queue',
    'dashboard.tableStatus': 'Table Status',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.browseMenuAction': 'Browse Menu',
    'dashboard.reorderFavorites': 'Reorder favorites',
    'dashboard.rateYourMeals': 'Rate your meals',
    'dashboard.savedItems': 'Saved items',
    'dashboard.discoverDeliciousMeals': 'Discover our delicious meals',
    'dashboard.freshAtlanticSalmon': 'Fresh Atlantic salmon with seasonal vegetables and lemon butter sauce',
    'dashboard.viewAllDishes': 'View all dishes',
    'dashboard.newVoiceOrderReceived': 'New voice order received',
    'dashboard.staffMemberClockedIn': 'Staff member clocked in',
    'dashboard.orderCompleted': 'Order completed',
    'dashboard.inventoryLowAlert': 'Inventory low alert',
    'dashboard.2MinutesAgo': '2 minutes ago',
    'dashboard.15MinutesAgo': '15 minutes ago',
    'dashboard.20MinutesAgo': '20 minutes ago',
    'dashboard.1HourAgo': '1 hour ago',
    'dashboard.ordersInQueue': 'orders in queue',
    'dashboard.manageAllDrinkOrders': 'Manage all drink orders',
    
    // Orders
    'orders.title': 'Orders',
    'orders.myOrders': 'My Orders',
    'orders.allOrders': 'All Orders',
    'orders.newOrder': 'New Order',
    'orders.editOrder': 'Edit Order',
    'orders.orderNumber': 'Order #',
    'orders.customer': 'Customer',
    'orders.table': 'Table',
    'orders.items': 'Items',
    'orders.orderStatus': 'Order Status',
    'orders.pending': 'Pending',
    'orders.preparing': 'Preparing',
    'orders.ready': 'Ready',
    'orders.served': 'Served',
    'orders.completed': 'Completed',
    'orders.createOrder': 'Create Order',
    'orders.updateOrder': 'Update Order',
    'orders.orderDetails': 'Order Details',
    'orders.specialInstructions': 'Special Instructions',
    'orders.orderItems': 'Order Items',
    'orders.addItems': 'Add Items',
    'orders.removeItem': 'Remove Item',
    'orders.editOrderTitle': 'Edit Order',
    'orders.modifyOrderDetails': 'Modify order details and items',
    'orders.orderInformation': 'Order Information',
    'orders.saveChanges': 'Save Changes',
    'orders.orderUpdated': 'Order updated successfully!',
    'orders.noOrdersFound': 'No orders found',
    'orders.trackOrderHistory': 'Track your order history and status',
    'orders.manageAssignedOrders': 'Manage orders assigned to you',
    'orders.monitorAllOrders': 'Monitor and manage all restaurant orders',
    'orders.markAsServed': 'Mark as served',
    'orders.markAsReady': 'Mark as ready',
    'orders.markAsPreparing': 'Mark as preparing',
    'orders.reorder': 'Reorder',
    'orders.orderSummary': 'Order Summary',
    'orders.createOrderForTable': 'Create order for Table',
    'orders.createNewOrderForTable': 'Create a new order for your table',
    'orders.autoGeneratesGuest': 'auto-generates guest name',
    'orders.enterCustomerName': 'Enter customer name (optional)',
    'orders.enterTableNumber': 'Enter table number (optional)',
    'orders.each': 'each',
    'orders.noItemsAdded': 'No items added yet',
    'orders.selectItemsFromMenu': 'Select items from the menu',
    'orders.pleaseAddItems': 'Please add at least one item to the order',
    'orders.validTableNumber': 'Please enter a valid table number or leave empty',
    'orders.removedItems': 'Removed Items',
    'orders.restore': 'Restore',
    
    // Menu
    'menu.title': 'Menu',
    'menu.ourMenu': 'Our Menu',
    'menu.menuManagement': 'Menu Management',
    'menu.addMenuItem': 'Add Menu Item',
    'menu.available': 'Available',
    'menu.unavailable': 'Unavailable',
    'menu.addToCart': 'Add to Cart',
    'menu.category': 'Category',
    'menu.description': 'Description',
    'menu.allCategories': 'All Categories',
    'menu.searchMenuItems': 'Search menu items...',
    'menu.manageMenuItems': 'Manage your restaurant menu items',
    'menu.discoverOfferings': 'Discover our delicious offerings',
    'menu.noMenuItems': 'No menu items found',
    'menu.adjustFilters': 'Try adjusting your search or filter criteria',
    'menu.noItemsAvailable': 'No menu items are currently available',
    'menu.clearFilters': 'Clear Filters',
    'menu.addFirstMenuItem': 'Add First Menu Item',
    'menu.editMenuItem': 'Edit Menu Item',
    'menu.updateItemDetails': 'Update item details',
    'menu.menuItemName': 'Menu Item Name',
    'menu.menuItemNamePlaceholder': 'e.g., Margherita Pizza',
    'menu.descriptionPlaceholder': 'Describe the menu item, ingredients, or special features...',
    'menu.priceLabel': 'Price (€)',
    'menu.availableForOrdering': 'Available for ordering',
    'menu.createMenuItem': 'Create Menu Item',
    'menu.preview': 'Preview',
    'menu.menuItemCreated': 'Menu item created successfully!',
    'menu.redirectingToMenu': 'Redirecting to menu page...',
    'menu.itemImage': 'Item Image',
    'menu.upload': 'Upload',
    'menu.aiGenerate': 'AI Generate',
    'menu.noImageAvailable': 'No image available',
    'menu.generatingAiImage': 'Generating AI image...',
    'menu.itemDetails': 'Item Details',
    'menu.ingredients': 'Ingredients',
    'menu.allergenInformation': 'Allergen Information',
    'menu.noKnownAllergens': 'No known allergens',
    'menu.viewDetails': 'View Details',
    'menu.markAsUnavailable': 'Mark as unavailable',
    'menu.markAsAvailable': 'Mark as available',
    'menu.availableMenuItems': 'Available Menu Items',
    
    // Tables
    'tables.title': 'Table Layout',
    'tables.floorPlan': 'Restaurant Floor Plan',
    'tables.available': 'Available',
    'tables.occupied': 'Occupied',
    'tables.reserved': 'Reserved',
    'tables.cleaning': 'Cleaning',
    'tables.seatNumber': 'Seat Number',
    'tables.editTables': 'Edit Tables',
    'tables.doneEditing': 'Done Editing',
    'tables.tableNumber': 'Table Number',
    'tables.numberOfSeats': 'Number of Seats',
    'tables.tableShape': 'Table Shape',
    'tables.tableStatus': 'Table Status',
    'tables.round': 'Round',
    'tables.square': 'Square',
    'tables.rectangle': 'Rectangle',
    'tables.oval': 'Oval',
    'tables.preview': 'Preview',
    'tables.saveChanges': 'Save Changes',
    'tables.editTable': 'Edit Table',
    'tables.viewOrders': 'View Orders',
    'tables.table': 'Table',
    'tables.seats': 'seats',
    'tables.seat': 'Seat',
    'tables.shape': 'Shape',
    'tables.capacity': 'Capacity',
    'tables.maxSeats': 'Maximum 20 seats per table',
    'tables.customizeProperties': 'Customize table properties',
    'tables.editMode': 'Edit Mode',
    'tables.quickActions': 'Quick Actions',
    'tables.editModeDescription': 'Edit mode: Click tables to modify their properties',
    'tables.interactiveDescription': 'Interactive restaurant floor plan - click tables or seats to take orders',
    'tables.editModeInstructions': 'Click on tables to edit their shape, seat count, and properties.',
    'tables.orderInstructions': 'Click on a table to create a general order, or click on specific seat numbers to create seat-specific orders.',
    'tables.clickToEdit': 'Click tables to edit properties',
    'tables.changeProperties': 'Change shape, seats, and status',
    'tables.clickDoneWhenFinished': 'Click "Done Editing" when finished',
    'tables.clickTableForOrder': 'Click table for general order',
    'tables.clickSeatForSpecific': 'Click seat number for seat-specific order',
    'tables.shapesRepresentTypes': 'Different shapes represent table types',
    'tables.redBadgeShowsOrders': 'Red badge shows active order count',
    
    // AI
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Chat with AI about your restaurant data',
    'ai.clearChat': 'Clear Chat',
    'ai.clearing': 'Clearing...',
    'ai.welcome': 'Welcome to AI Assistant',
    'ai.startConversation': 'Start a conversation by typing your message below.',
    'ai.typeMessage': 'Type your message...',
    'ai.aiThinking': 'AI is thinking...',
    'ai.typing': 'Typing...',
    'ai.chatWithAi': 'Chat with AI about your restaurant data',
    'ai.serviceUnavailable': 'Service Temporarily Unavailable',
    'ai.backendUnavailable': 'AI backend unavailable',
    'ai.poweredByAi': 'Powered by Advanced AI',
    
    // Voice Order
    'voice.title': 'Voice Order Assistant',
    'voice.subtitle': 'Speak your order naturally and let AI handle the rest',
    'voice.step1': 'Step 1: Record Your Order',
    'voice.step2': 'Step 2: Review Transcript',
    'voice.step3': 'Step 3: Confirm Order Details',
    'voice.startRecording': 'Start Recording',
    'voice.stopRecording': 'Stop Recording',
    'voice.listening': 'Listening... Speak your order clearly',
    'voice.processOrder': 'Process Order with AI',
    'voice.processing': 'Processing with AI...',
    'voice.createOrder': 'Create Order',
    'voice.creating': 'Creating Order...',
    'voice.clickStartRecording': 'Click "Start Recording" and speak your order naturally',
    'voice.speechNotSupported': 'Speech recognition not available in this browser',
    'voice.exampleOrders': 'Example orders',
    'voice.example1': '"Table 5 wants two margherita pizzas and one caesar salad please."',
    'voice.example2': '"One grilled salmon, no sauce, and two house wines for table 3."',
    'voice.example3': '"Two chicken alfredo and one chocolate cake."',
    'voice.anonymousOrder': '(anonymous order)',
    'voice.reviewTranscript': 'Review Transcript',
    'voice.confirmOrderDetails': 'Confirm Order Details',
    'voice.customerNameOptional': 'Customer Name (optional - auto-generates guest name)',
    'voice.tableNumberOptional': 'Table Number (optional)',
    'voice.orderItems': 'Order Items',
    'voice.notOnMenu': 'Not on menu',
    'voice.specialInstructions': 'Special Instructions',
    'voice.voiceTranscript': 'Voice transcript',
    'voice.orderParsedSuccessfully': 'Order parsed successfully!',
    'voice.reviewAndConfirm': 'Review and confirm below.',
    'voice.voiceOrderCreated': 'Voice order created successfully!',
    'voice.menuStatus': 'Menu Status',
    'voice.itemsLoaded': 'items loaded',
    'voice.speechRecognitionNotSupported': 'Speech Recognition Not Supported',
    'voice.useChromeEdgeSafari': 'Please use Chrome, Edge or Safari for voice ordering.',
    'voice.grantMicrophoneAccess': 'Grant Microphone Access',
    'voice.microphoneRequired': 'Microphone access is required for voice ordering. Please allow microphone access in your browser settings.',
    'voice.noSpeechDetected': 'No speech detected. Please try recording again.',
    'voice.speakClearlyTryAgain': 'AI could not understand the order. Please try speaking more clearly or use simpler language.',
    'voice.noValidMenuItems': 'No menu items could be matched from your order. Please try again with clearer item names.',
    'voice.speechRecognitionError': 'Speech recognition error',
    'voice.noMicrophoneFound': 'No microphone found. Please check your microphone connection.',
    'voice.failedToInitialize': 'Failed to initialize speech recognition',
    'voice.failedToStartRecording': 'Failed to start recording. Please check microphone permissions.',
    'voice.failedToPlayAudio': 'Failed to play audio',
    'voice.failedToProcessOrder': 'Failed to process voice order. Please try again.',
    'voice.invalidOrderFormat': 'Invalid order format: items array missing',
    'voice.noItemsFound': 'No items found in the order',
    'voice.noOrderToCreate': 'No order to create or user not authenticated',
    'voice.noValidMenuItemsFound': 'No valid menu items found in the order',
    'voice.noMenuItemsAvailable': 'No menu items available. Please ensure menu items are loaded.',
    'voice.voiceOrder': 'Voice order',
    'voice.play': 'Play',
    'voice.pause': 'Pause',
    'voice.reset': 'Reset',
    
    // Quick Order
    'quickOrder.title': 'Quick Order Voice Assistant',
    'quickOrder.subtitle': 'Speak your order and let the system automatically generate an invoice',
    'quickOrder.step1': 'Step 1: Record Your Order',
    'quickOrder.step2': 'Step 2: Review Transcript',
    'quickOrder.step3': 'Step 3: Confirm Order Details',
    'quickOrder.step4': 'Step 4: Generate and Send Invoice',
    'quickOrder.startRecordingPrompt': 'Click "Start Recording" and speak your order naturally',
    'quickOrder.processWithAI': 'Process Order with AI',
    'quickOrder.createOrder': 'Create Order',
    'quickOrder.customerNameOptional': 'Customer Name (optional - auto-generates guest name)',
    'quickOrder.tableNumberOptional': 'Table Number (optional)',
    'quickOrder.orderItems': 'Order Items',
    'quickOrder.subtotal': 'Subtotal',
    'quickOrder.vat': 'VAT',
    'quickOrder.net': 'Net',
    'quickOrder.invoiceDetails': 'Invoice Details',
    'quickOrder.invoiceNumber': 'Invoice Number',
    'quickOrder.pdfInvoice': 'PDF Invoice',
    'quickOrder.sendEmail': 'Send Email',
    'quickOrder.datevExport': 'DATEV Export',
    'quickOrder.automaticSending': 'Automatic Sending',
    'quickOrder.invoiceWillBeSent': 'Invoice will be automatically sent to',
    'quickOrder.workflow': 'Quick Mode: Voice → AI Analysis → Order → Invoice → Email',
    'quickOrder.companyInfo': 'Company Information',
    'quickOrder.editCompanyInfo': 'Edit Company Information',
    'quickOrder.invoiceGenerated': 'Invoice successfully generated and downloaded!',
    'quickOrder.invoiceGenerationError': 'Error generating invoice',
    'quickOrder.invoiceEmailSent': 'Invoice successfully sent to accountant by email!',
    'quickOrder.emailSendingError': 'Error sending email',
    'quickOrder.datevExportGenerated': 'DATEV export successfully generated and downloaded!',
    'quickOrder.datevExportError': 'Error generating DATEV export',
    'quickOrder.example1': '"Two beers, one currywurst with fries, one Fanta"',
    'quickOrder.example2': '"Table 5 would like two margherita pizzas and a Caesar salad"',
    'quickOrder.example3': '"One grilled salmon without sauce and two house wines for table 3"',
    
    // Reports
    'reports.title': 'Sales Report',
    'reports.subtitle': 'Comprehensive overview of bills and revenue',
    'reports.exportCsv': 'Export CSV',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.statusFilter': 'Status Filter',
    'reports.allStatus': 'All Status',
    'reports.totalBills': 'Total Bills',
    'reports.totalRevenue': 'Total Revenue',
    'reports.averageBill': 'Average Bill',
    'reports.growthRate': 'Growth Rate',
    'reports.dailyRevenueTrend': 'Daily Revenue Trend',
    'reports.billsOverview': 'Bills Overview',
    'reports.billNumber': 'Bill Number',
    'reports.dateTime': 'Date & Time',
    'reports.noBillsFound': 'No bills found',
    'reports.adjustDateRange': 'No bills match your current filters. Try adjusting the date range or status filter.',
    'reports.accessDenied': 'Access Denied',
    'reports.managersOnly': 'Only managers can access sales reports.',
    'reports.loadingReport': 'Loading sales report...',
    'reports.errorLoadingReport': 'Error Loading Report',
    'reports.today': 'Today:',
    'reports.bills': 'bills',
    'reports.perTransaction': 'Per transaction',
    'reports.vsPreviousPeriod': 'vs previous period',
    'reports.noDataAvailable': 'No data available for the selected period',
    'reports.billsFound': 'bills found',
    
    // Staff
    'staff.title': 'Staff Overview',
    'staff.comingSoon': 'Staff overview coming soon...',
    
    // Inventory
    'inventory.title': 'Inventory View',
    'inventory.comingSoon': 'Inventory view coming soon...',
    
    // Cart
    'cart.title': 'Cart/Checkout',
    'cart.comingSoon': 'Cart/checkout coming soon...',
    
    // Bar Dashboard
    'bar.soundOn': 'Sound On',
    'bar.soundOff': 'Sound Off',
    'bar.enableNotifications': 'Enable notifications',
    'bar.disableNotifications': 'Disable notifications',
    'bar.start': 'Start',
    'bar.ready': 'Ready',
    'bar.readyForPickup': 'Ready for pickup',
    'bar.unknownDrink': 'Unknown Drink',
    'bar.noDrinkOrders': 'No Drink Orders',
    'bar.allCaughtUp': 'All caught up! No pending drink orders at the moment.',
    'bar.allDrinkOrders': 'All Drink Orders',
    'bar.realTimeUpdates': 'Real-time updates',
    'bar.barMenu': 'Bar Menu',
    'bar.viewAllBeverages': 'View all beverages',
    
    // Errors and Messages
    'error.loadingFailed': 'Loading failed',
    'error.tryAgain': 'Try Again',
    'error.accessDenied': 'Access Denied',
    'error.notFound': 'Not found',
    'error.networkError': 'Network error. Please check your connection.',
    'error.seatsRange': 'Seats must be between 1 and 20',
    'error.tableNumberInvalid': 'Table number must be greater than 0',
    'error.menuLoadingError': 'Menu Loading Error',
    'error.ordersLoadingError': 'Orders Loading Error',
    'error.userNotFound': 'User not found',
    'error.unexpectedError': 'An unexpected error occurred',
    'error.failedToLoad': 'Failed to load',
    'error.noMenuItems': 'No menu items available at the moment.',
    'error.refreshMenu': 'Refresh Menu',
    'error.addMenuItemsFirst': 'Please add menu items first.',
    'error.failedToCreate': 'Failed to create order',
    'error.failedToAddItems': 'Failed to add items to order',
    'error.failedToUpdate': 'Failed to update order',
    'success.orderCreated': 'Order created successfully!',
    'success.orderUpdated': 'Order updated successfully!',
    'success.itemAdded': 'Item added to cart!',
    'success.menuItemCreated': 'Menu item created successfully!',
    'success.menuItemUpdated': 'Menu item updated successfully!',
    'success.menuItemDeleted': 'Menu item deleted successfully',
    'success.tableUpdated': 'Table updated successfully!',
    'success.chatCleared': 'Chat cleared successfully',
  },
  de: {
    // Login/Auth
    'auth.title': 'RestaurantOS',
    'auth.subtitle': 'Professionelle Restaurant-Verwaltung',
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.createAccount': 'Konto erstellen',
    'auth.fullName': 'Vollständiger Name',
    'auth.fullNamePlaceholder': 'Geben Sie Ihren vollständigen Namen ein',
    'auth.role': 'Rolle',
    'auth.email': 'E-Mail',
    'auth.emailPlaceholder': 'Geben Sie Ihre E-Mail ein',
    'auth.password': 'Passwort',
    'auth.passwordPlaceholder': 'Geben Sie Ihr Passwort ein (min. 6 Zeichen)',
    'auth.language': 'Sprache',
    'auth.demoAccounts': 'Demo-Konten (erstellen Sie neue oder verwenden Sie diese zum Testen):',
    'auth.loading': 'RestaurantOS wird geladen',
    'auth.settingUp': 'Ihr Restaurant-Management-System wird eingerichtet...',
    
    // Roles
    'role.customer': 'Kunde',
    'role.waiter': 'Kellner',
    'role.kitchen': 'Küchenpersonal',
    'role.manager': 'Manager',
    
    // Categories
    'category.Food': 'Essen',
    'category.Drink': 'Getränk',
    'category.Dessert': 'Dessert',
    'category.Appetizer': 'Vorspeise',
    'category.Main Course': 'Hauptgang',
    'category.Side Dish': 'Beilage',
    'category.Beverage': 'Getränk',
    'category.Alcohol': 'Alkohol',
    'category.Coffee': 'Kaffee',
    'category.Tea': 'Tee',
    'category.Salads': 'Salate',
    'category.Desserts': 'Desserts',
    'category.Beverages': 'Getränke',
    
    // Common
    'common.welcome': 'Willkommen',
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.add': 'Hinzufügen',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.refresh': 'Aktualisieren',
    'common.logout': 'Abmelden',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.total': 'Gesamt',
    'common.price': 'Preis',
    'common.quantity': 'Menge',
    'common.status': 'Status',
    'common.notes': 'Notizen',
    'common.optional': 'optional',
    'common.details': 'Details',
    'common.legend': 'Legende',
    'common.howToUse': 'Verwendung',
    'common.clickToView': 'Klicken zum Anzeigen',
    'common.clickToEdit': 'Klicken zum Bearbeiten',
    'common.clickToOrder': 'Klicken um für diesen Platz zu bestellen',
    'common.viewAll': 'Alle anzeigen',
    'common.tryAgain': 'Erneut versuchen',
    'common.name': 'Name',
    'common.description': 'Beschreibung',
    'common.category': 'Kategorie',
    'common.available': 'Verfügbar',
    'common.unavailable': 'Nicht verfügbar',
    'common.customer': 'Kunde',
    'common.table': 'Tisch',
    'common.time': 'Zeit',
    'common.date': 'Datum',
    'common.items': 'Artikel',
    'common.guest': 'Gast',
    
    // Navigation - Desktop
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Bestellungen',
    'nav.menu': 'Speisekarte',
    'nav.tables': 'Tische',
    'nav.reports': 'Berichte',
    'nav.staff': 'Personal',
    'nav.ai': 'KI-Assistent',
    'nav.ordersOverview': 'Bestellungsübersicht',
    'nav.menuManagement': 'Speisekarten-Verwaltung',
    'nav.takeOrder': 'Bestellung aufnehmen',
    'nav.quickOrder': 'Quick-Bestellung',
    'nav.tableView': 'Tischansicht',
    'nav.staffOverview': 'Personalübersicht',
    'nav.salesReports': 'Verkaufsberichte',
    'nav.pendingOrders': 'Ausstehende Bestellungen',
    'nav.inventoryView': 'Lagerbestand',
    'nav.cartCheckout': 'Warenkorb/Kasse',
    'nav.aiAgent': 'KI-Agent',
    'nav.myOrders': 'Meine Bestellungen',
    'nav.browseMenu': 'Speisekarte durchsuchen',
    'nav.drinkOrders': 'Getränkebestellungen',
    'nav.barInventory': 'Bar-Lagerbestand',
    'nav.barMenu': 'Bar-Menü',
    
    // Navigation - Mobile (shorter labels)
    'nav.order': 'Bestellen',
    'nav.pending': 'Ausstehend',
    'nav.done': 'Fertig',
    'nav.stock': 'Lager',
    'nav.cart': 'Warenkorb',
    'nav.quick': 'Quick',
    'nav.drinks': 'Getränke',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.todaysSpecial': 'Tagesangebot',
    'dashboard.orderNow': 'Jetzt bestellen',
    'dashboard.browseMenu': 'Speisekarte durchsuchen',
    'dashboard.quickOrder': 'Schnellbestellung',
    'dashboard.reviews': 'Bewertungen',
    'dashboard.favorites': 'Favoriten',
    'dashboard.featuredItems': 'Empfohlene Gerichte',
    'dashboard.recentOrders': 'Letzte Bestellungen',
    'dashboard.noOrders': 'Sie haben noch keine Bestellungen aufgegeben',
    'dashboard.managerDashboard': 'Manager Dashboard',
    'dashboard.waiterDashboard': 'Kellner Dashboard',
    'dashboard.kitchenDashboard': 'Küchen Dashboard',
    'dashboard.customerDashboard': 'Kunden Dashboard',
    'dashboard.todaysRevenue': 'Heutiger Umsatz',
    'dashboard.ordersToday': 'Bestellungen heute',
    'dashboard.activeStaff': 'Aktives Personal',
    'dashboard.avgOrderTime': 'Ø Bestellzeit',
    'dashboard.salesTrend': 'Umsatztrend',
    'dashboard.recentActivity': 'Letzte Aktivitäten',
    'dashboard.pendingOrders': 'Ausstehende Bestellungen',
    'dashboard.completedToday': 'Heute abgeschlossen',
    'dashboard.avgPrepTime': 'Ø Zubereitungszeit',
    'dashboard.lowStockItems': 'Niedrige Lagerbestände',
    'dashboard.orderQueue': 'Bestellwarteschlange',
    'dashboard.tableStatus': 'Tischstatus',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.browseMenuAction': 'Speisekarte durchsuchen',
    'dashboard.reorderFavorites': 'Favoriten nachbestellen',
    'dashboard.rateYourMeals': 'Bewerten Sie Ihre Mahlzeiten',
    'dashboard.savedItems': 'Gespeicherte Artikel',
    'dashboard.discoverDeliciousMeals': 'Entdecken Sie unsere köstlichen Gerichte',
    'dashboard.freshAtlanticSalmon': 'Frischer Atlantiklachs mit Saisongemüse und Zitronen-Butter-Sauce',
    'dashboard.viewAllDishes': 'Alle Gerichte anzeigen',
    'dashboard.newVoiceOrderReceived': 'Neue Sprachbestellung erhalten',
    'dashboard.staffMemberClockedIn': 'Mitarbeiter hat sich angemeldet',
    'dashboard.orderCompleted': 'Bestellung abgeschlossen',
    'dashboard.inventoryLowAlert': 'Lagerbestand niedrig',
    'dashboard.2MinutesAgo': 'vor 2 Minuten',
    'dashboard.15MinutesAgo': 'vor 15 Minuten',
    'dashboard.20MinutesAgo': 'vor 20 Minuten',
    'dashboard.1HourAgo': 'vor 1 Stunde',
    'dashboard.ordersInQueue': 'Bestellungen in der Warteschlange',
    'dashboard.manageAllDrinkOrders': 'Verwalten Sie alle Getränkebestellungen',
    
    // Orders
    'orders.title': 'Bestellungen',
    'orders.myOrders': 'Meine Bestellungen',
    'orders.allOrders': 'Alle Bestellungen',
    'orders.newOrder': 'Neue Bestellung',
    'orders.editOrder': 'Bestellung bearbeiten',
    'orders.orderNumber': 'Bestellung Nr. ',
    'orders.customer': 'Kunde',
    'orders.table': 'Tisch',
    'orders.items': 'Artikel',
    'orders.orderStatus': 'Bestellstatus',
    'orders.pending': 'Ausstehend',
    'orders.preparing': 'In Vorbereitung',
    'orders.ready': 'Bereit',
    'orders.served': 'Serviert',
    'orders.completed': 'Abgeschlossen',
    'orders.createOrder': 'Bestellung erstellen',
    'orders.updateOrder': 'Bestellung aktualisieren',
    'orders.orderDetails': 'Bestelldetails',
    'orders.specialInstructions': 'Besondere Anweisungen',
    'orders.orderItems': 'Bestellartikel',
    'orders.addItems': 'Artikel hinzufügen',
    'orders.removeItem': 'Artikel entfernen',
    'orders.editOrderTitle': 'Bestellung bearbeiten',
    'orders.modifyOrderDetails': 'Bestelldetails und Artikel ändern',
    'orders.orderInformation': 'Bestellinformationen',
    'orders.saveChanges': 'Änderungen speichern',
    'orders.orderUpdated': 'Bestellung erfolgreich aktualisiert!',
    'orders.noOrdersFound': 'Keine Bestellungen gefunden',
    'orders.trackOrderHistory': 'Verfolgen Sie Ihren Bestellverlauf und Status',
    'orders.manageAssignedOrders': 'Verwalten Sie Ihnen zugewiesene Bestellungen',
    'orders.monitorAllOrders': 'Überwachen und verwalten Sie alle Restaurant-Bestellungen',
    'orders.markAsServed': 'Als serviert markieren',
    'orders.markAsReady': 'Als bereit markieren',
    'orders.markAsPreparing': 'Als in Vorbereitung markieren',
    'orders.reorder': 'Nachbestellen',
    'orders.orderSummary': 'Bestellübersicht',
    'orders.createOrderForTable': 'Bestellung für Tisch erstellen',
    'orders.createNewOrderForTable': 'Neue Bestellung für Ihren Tisch erstellen',
    'orders.autoGeneratesGuest': 'generiert automatisch Gastnamen',
    'orders.enterCustomerName': 'Kundennamen eingeben (optional)',
    'orders.enterTableNumber': 'Tischnummer eingeben (optional)',
    'orders.each': 'je',
    'orders.noItemsAdded': 'Noch keine Artikel hinzugefügt',
    'orders.selectItemsFromMenu': 'Wählen Sie Artikel aus der Speisekarte',
    'orders.pleaseAddItems': 'Bitte fügen Sie mindestens einen Artikel zur Bestellung hinzu',
    'orders.validTableNumber': 'Bitte geben Sie eine gültige Tischnummer ein oder lassen Sie das Feld leer',
    'orders.removedItems': 'Entfernte Artikel',
    'orders.restore': 'Wiederherstellen',
    
    // Menu
    'menu.title': 'Speisekarte',
    'menu.ourMenu': 'Unsere Speisekarte',
    'menu.menuManagement': 'Speisekarten-Verwaltung',
    'menu.addMenuItem': 'Menüpunkt hinzufügen',
    'menu.available': 'Verfügbar',
    'menu.unavailable': 'Nicht verfügbar',
    'menu.addToCart': 'In den Warenkorb',
    'menu.category': 'Kategorie',
    'menu.description': 'Beschreibung',
    'menu.allCategories': 'Alle Kategorien',
    'menu.searchMenuItems': 'Menüpunkte suchen...',
    'menu.manageMenuItems': 'Verwalten Sie Ihre Restaurant-Menüpunkte',
    'menu.discoverOfferings': 'Entdecken Sie unsere köstlichen Angebote',
    'menu.noMenuItems': 'Keine Menüpunkte gefunden',
    'menu.adjustFilters': 'Versuchen Sie, Ihre Such- oder Filterkriterien anzupassen',
    'menu.noItemsAvailable': 'Derzeit sind keine Menüpunkte verfügbar',
    'menu.clearFilters': 'Filter löschen',
    'menu.addFirstMenuItem': 'Ersten Menüpunkt hinzufügen',
    'menu.editMenuItem': 'Menüpunkt bearbeiten',
    'menu.updateItemDetails': 'Artikeldetails aktualisieren',
    'menu.menuItemName': 'Menüpunkt-Name',
    'menu.menuItemNamePlaceholder': 'z.B. Margherita Pizza',
    'menu.descriptionPlaceholder': 'Beschreiben Sie den Menüpunkt, Zutaten oder besondere Eigenschaften...',
    'menu.priceLabel': 'Preis (€)',
    'menu.availableForOrdering': 'Verfügbar für Bestellungen',
    'menu.createMenuItem': 'Menüpunkt erstellen',
    'menu.preview': 'Vorschau',
    'menu.menuItemCreated': 'Menüpunkt erfolgreich erstellt!',
    'menu.redirectingToMenu': 'Weiterleitung zur Speisekarte...',
    'menu.itemImage': 'Artikel-Bild',
    'menu.upload': 'Hochladen',
    'menu.aiGenerate': 'KI generieren',
    'menu.noImageAvailable': 'Kein Bild verfügbar',
    'menu.generatingAiImage': 'KI-Bild wird generiert...',
    'menu.itemDetails': 'Artikeldetails',
    'menu.ingredients': 'Zutaten',
    'menu.allergenInformation': 'Allergen-Informationen',
    'menu.noKnownAllergens': 'Keine bekannten Allergene',
    'menu.viewDetails': 'Details anzeigen',
    'menu.markAsUnavailable': 'Als nicht verfügbar markieren',
    'menu.markAsAvailable': 'Als verfügbar markieren',
    'menu.availableMenuItems': 'Verfügbare Menüpunkte',
    
    // Tables
    'tables.title': 'Tischlayout',
    'tables.floorPlan': 'Restaurant-Grundriss',
    'tables.available': 'Verfügbar',
    'tables.occupied': 'Besetzt',
    'tables.reserved': 'Reserviert',
    'tables.cleaning': 'Reinigung',
    'tables.seatNumber': 'Sitzplatznummer',
    'tables.editTables': 'Tische bearbeiten',
    'tables.doneEditing': 'Bearbeitung beenden',
    'tables.tableNumber': 'Tischnummer',
    'tables.numberOfSeats': 'Anzahl der Sitzplätze',
    'tables.tableShape': 'Tischform',
    'tables.tableStatus': 'Tischstatus',
    'tables.round': 'Rund',
    'tables.square': 'Quadratisch',
    'tables.rectangle': 'Rechteckig',
    'tables.oval': 'Oval',
    'tables.preview': 'Vorschau',
    'tables.saveChanges': 'Änderungen speichern',
    'tables.editTable': 'Tisch bearbeiten',
    'tables.viewOrders': 'Bestellungen anzeigen',
    'tables.table': 'Tisch',
    'tables.seats': 'Plätze',
    'tables.seat': 'Platz',
    'tables.shape': 'Form',
    'tables.capacity': 'Kapazität',
    'tables.maxSeats': 'Maximal 20 Sitzplätze pro Tisch',
    'tables.customizeProperties': 'Tischeigenschaften anpassen',
    'tables.editMode': 'Bearbeitungsmodus',
    'tables.quickActions': 'Schnellaktionen',
    'tables.editModeDescription': 'Bearbeitungsmodus: Klicken Sie auf Tische, um ihre Eigenschaften zu ändern',
    'tables.interactiveDescription': 'Interaktiver Restaurant-Grundriss - klicken Sie auf Tische oder Sitzplätze, um Bestellungen aufzugeben',
    'tables.editModeInstructions': 'Klicken Sie auf Tische, um ihre Form, Sitzplatzanzahl und Eigenschaften zu bearbeiten.',
    'tables.orderInstructions': 'Klicken Sie auf einen Tisch für eine allgemeine Bestellung oder auf bestimmte Sitzplatznummern für sitzplatzspezifische Bestellungen.',
    'tables.clickToEdit': 'Tische anklicken zum Bearbeiten',
    'tables.changeProperties': 'Form, Sitzplätze und Status ändern',
    'tables.clickDoneWhenFinished': 'Klicken Sie "Bearbeitung beenden" wenn fertig',
    'tables.clickTableForOrder': 'Tisch für allgemeine Bestellung anklicken',
    'tables.clickSeatForSpecific': 'Sitzplatznummer für spezifische Bestellung anklicken',
    'tables.shapesRepresentTypes': 'Verschiedene Formen repräsentieren Tischtypen',
    'tables.redBadgeShowsOrders': 'Rotes Abzeichen zeigt aktive Bestellungsanzahl',
    
    // AI
    'ai.title': 'KI-Assistent',
    'ai.subtitle': 'Chatten Sie mit der KI über Ihre Restaurant-Daten',
    'ai.clearChat': 'Chat löschen',
    'ai.clearing': 'Wird gelöscht...',
    'ai.welcome': 'Willkommen beim KI-Assistenten',
    'ai.startConversation': 'Beginnen Sie eine Unterhaltung, indem Sie unten Ihre Nachricht eingeben.',
    'ai.typeMessage': 'Geben Sie Ihre Nachricht ein...',
    'ai.aiThinking': 'KI denkt nach...',
    'ai.typing': 'Tippt...',
    'ai.chatWithAi': 'Chatten Sie mit der KI über Ihre Restaurant-Daten',
    'ai.serviceUnavailable': 'Service vorübergehend nicht verfügbar',
    'ai.backendUnavailable': 'KI-Backend nicht verfügbar',
    'ai.poweredByAi': 'Angetrieben von fortschrittlicher KI',
    
    // Voice Order
    'voice.title': 'Sprach-Bestellassistent',
    'voice.subtitle': 'Sprechen Sie Ihre Bestellung natürlich und lassen Sie die KI den Rest erledigen',
    'voice.step1': 'Schritt 1: Bestellung aufnehmen',
    'voice.step2': 'Schritt 2: Transkript überprüfen',
    'voice.step3': 'Schritt 3: Bestelldetails bestätigen',
    'voice.startRecording': 'Aufnahme starten',
    'voice.stopRecording': 'Aufnahme stoppen',
    'voice.listening': 'Hört zu... Sprechen Sie Ihre Bestellung deutlich',
    'voice.processOrder': 'Bestellung mit KI verarbeiten',
    'voice.processing': 'Wird mit KI verarbeitet...',
    'voice.createOrder': 'Bestellung erstellen',
    'voice.creating': 'Bestellung wird erstellt...',
    'voice.clickStartRecording': 'Klicken Sie "Aufnahme starten" und sprechen Sie Ihre Bestellung natürlich',
    'voice.speechNotSupported': 'Spracherkennung in diesem Browser nicht verfügbar',
    'voice.exampleOrders': 'Beispielbestellungen',
    'voice.example1': '"Tisch 5 möchte zwei Margherita-Pizzen und einen Caesar-Salat bitte."',
    'voice.example2': '"Ein gegrillter Lachs, ohne Sauce, und zwei Hausweine für Tisch 3."',
    'voice.example3': '"Zwei Chicken Alfredo und einen Schokoladenkuchen."',
    'voice.anonymousOrder': '(anonyme Bestellung)',
    'voice.reviewTranscript': 'Transkript überprüfen',
    'voice.confirmOrderDetails': 'Bestelldetails bestätigen',
    'voice.customerNameOptional': 'Kundenname (optional - generiert automatisch Gastnamen)',
    'voice.tableNumberOptional': 'Tischnummer (optional)',
    'voice.orderItems': 'Bestellartikel',
    'voice.notOnMenu': 'Nicht auf der Speisekarte',
    'voice.specialInstructions': 'Besondere Anweisungen',
    'voice.voiceTranscript': 'Sprach-Transkript',
    'voice.orderParsedSuccessfully': 'Bestellung erfolgreich analysiert!',
    'voice.reviewAndConfirm': 'Überprüfen und bestätigen Sie unten.',
    'voice.voiceOrderCreated': 'Sprachbestellung erfolgreich erstellt!',
    'voice.menuStatus': 'Speisekarten-Status',
    'voice.itemsLoaded': 'Artikel geladen',
    'voice.speechRecognitionNotSupported': 'Spracherkennung nicht unterstützt',
    'voice.useChromeEdgeSafari': 'Bitte verwenden Sie Chrome, Edge oder Safari für Sprachbestellungen.',
    'voice.grantMicrophoneAccess': 'Mikrofonzugriff gewähren',
    'voice.microphoneRequired': 'Mikrofonzugriff ist für Sprachbestellungen erforderlich. Bitte erlauben Sie den Mikrofonzugriff in Ihren Browser-Einstellungen.',
    'voice.noSpeechDetected': 'Keine Sprache erkannt. Bitte versuchen Sie es erneut.',
    'voice.speakClearlyTryAgain': 'Die KI konnte die Bestellung nicht verstehen. Bitte versuchen Sie deutlicher zu sprechen oder verwenden Sie einfachere Sprache.',
    'voice.noValidMenuItems': 'Keine Menüpunkte konnten aus Ihrer Bestellung zugeordnet werden. Bitte versuchen Sie es mit klareren Artikelnamen erneut.',
    'voice.speechRecognitionError': 'Spracherkennungsfehler',
    'voice.noMicrophoneFound': 'Kein Mikrofon gefunden. Bitte überprüfen Sie Ihre Mikrofonverbindung.',
    'voice.failedToInitialize': 'Spracherkennung konnte nicht initialisiert werden',
    'voice.failedToStartRecording': 'Aufnahme konnte nicht gestartet werden. Bitte überprüfen Sie die Mikrofonberechtigungen.',
    'voice.failedToPlayAudio': 'Audio konnte nicht abgespielt werden',
    'voice.failedToProcessOrder': 'Sprachbestellung konnte nicht verarbeitet werden. Bitte versuchen Sie es erneut.',
    'voice.invalidOrderFormat': 'Ungültiges Bestellformat: Artikel-Array fehlt',
    'voice.noItemsFound': 'Keine Artikel in der Bestellung gefunden',
    'voice.noOrderToCreate': 'Keine Bestellung zu erstellen oder Benutzer nicht authentifiziert',
    'voice.noValidMenuItemsFound': 'Keine gültigen Menüpunkte in der Bestellung gefunden',
    'voice.noMenuItemsAvailable': 'Keine Menüpunkte verfügbar. Bitte stellen Sie sicher, dass Menüpunkte geladen sind.',
    'voice.voiceOrder': 'Sprachbestellung',
    'voice.play': 'Abspielen',
    'voice.pause': 'Pause',
    'voice.reset': 'Zurücksetzen',
    
    // Quick Order
    'quickOrder.title': 'Quick-Modus Sprachbestellung',
    'quickOrder.subtitle': 'Sprechen Sie Ihre Bestellung und lassen Sie das System automatisch eine Rechnung generieren',
    'quickOrder.step1': 'Schritt 1: Bestellung aufnehmen',
    'quickOrder.step2': 'Schritt 2: Transkript überprüfen',
    'quickOrder.step3': 'Schritt 3: Bestelldetails bestätigen',
    'quickOrder.step4': 'Schritt 4: Rechnung generieren und versenden',
    'quickOrder.startRecordingPrompt': 'Klicken Sie "Aufnahme starten" und sprechen Sie Ihre Bestellung natürlich',
    'quickOrder.processWithAI': 'Bestellung mit KI verarbeiten',
    'quickOrder.createOrder': 'Bestellung erstellen',
    'quickOrder.customerNameOptional': 'Kundenname (optional - generiert automatisch Gastnamen)',
    'quickOrder.tableNumberOptional': 'Tischnummer (optional)',
    'quickOrder.orderItems': 'Bestellartikel',
    'quickOrder.subtotal': 'Zwischensumme',
    'quickOrder.vat': 'MwSt',
    'quickOrder.net': 'Netto',
    'quickOrder.invoiceDetails': 'Rechnungsdetails',
    'quickOrder.invoiceNumber': 'Rechnungsnummer',
    'quickOrder.pdfInvoice': 'PDF Rechnung',
    'quickOrder.sendEmail': 'E-Mail senden',
    'quickOrder.datevExport': 'DATEV Export',
    'quickOrder.automaticSending': 'Automatischer Versand',
    'quickOrder.invoiceWillBeSent': 'Rechnung wird automatisch gesendet an',
    'quickOrder.workflow': 'Quick-Modus: Sprache → KI-Analyse → Bestellung → Rechnung → E-Mail',
    'quickOrder.companyInfo': 'Firmeninformationen',
    'quickOrder.editCompanyInfo': 'Firmeninformationen bearbeiten',
    'quickOrder.invoiceGenerated': 'Rechnung erfolgreich generiert und heruntergeladen!',
    'quickOrder.invoiceGenerationError': 'Fehler beim Generieren der Rechnung',
    'quickOrder.invoiceEmailSent': 'Rechnung erfolgreich per E-Mail an Steuerberater gesendet!',
    'quickOrder.emailSendingError': 'Fehler beim Versenden der E-Mail',
    'quickOrder.datevExportGenerated': 'DATEV-Export erfolgreich generiert und heruntergeladen!',
    'quickOrder.datevExportError': 'Fehler beim Generieren des DATEV-Exports',
    'quickOrder.example1': '"Zwei Bier, eine Currywurst mit Pommes, eine Fanta"',
    'quickOrder.example2': '"Tisch 5 möchte zwei Margherita-Pizzen und einen Caesar-Salat"',
    'quickOrder.example3': '"Ein gegrillter Lachs ohne Sauce und zwei Hausweine für Tisch 3"',
    
    // Reports
    'reports.title': 'Verkaufsbericht',
    'reports.subtitle': 'Umfassender Überblick über Rechnungen und Umsatz',
    'reports.exportCsv': 'CSV exportieren',
    'reports.startDate': 'Startdatum',
    'reports.endDate': 'Enddatum',
    'reports.statusFilter': 'Status-Filter',
    'reports.allStatus': 'Alle Status',
    'reports.totalBills': 'Gesamtrechnungen',
    'reports.totalRevenue': 'Gesamtumsatz',
    'reports.averageBill': 'Durchschnittsrechnung',
    'reports.growthRate': 'Wachstumsrate',
    'reports.dailyRevenueTrend': 'Täglicher Umsatztrend',
    'reports.billsOverview': 'Rechnungsübersicht',
    'reports.billNumber': 'Rechnungsnummer',
    'reports.dateTime': 'Datum & Zeit',
    'reports.noBillsFound': 'Keine Rechnungen gefunden',
    'reports.adjustDateRange': 'Keine Rechnungen entsprechen Ihren aktuellen Filtern. Versuchen Sie, den Datumsbereich oder Statusfilter anzupassen.',
    'reports.accessDenied': 'Zugriff verweigert',
    'reports.managersOnly': 'Nur Manager können auf Verkaufsberichte zugreifen.',
    'reports.loadingReport': 'Verkaufsbericht wird geladen...',
    'reports.errorLoadingReport': 'Fehler beim Laden des Berichts',
    'reports.today': 'Heute:',
    'reports.bills': 'Rechnungen',
    'reports.perTransaction': 'Pro Transaktion',
    'reports.vsPreviousPeriod': 'vs. vorherige Periode',
    'reports.noDataAvailable': 'Keine Daten für den ausgewählten Zeitraum verfügbar',
    'reports.billsFound': 'Rechnungen gefunden',
    
    // Staff
    'staff.title': 'Personalübersicht',
    'staff.comingSoon': 'Personalübersicht kommt bald...',
    
    // Inventory
    'inventory.title': 'Lagerbestand',
    'inventory.comingSoon': 'Lagerbestandsansicht kommt bald...',
    
    // Cart
    'cart.title': 'Warenkorb/Kasse',
    'cart.comingSoon': 'Warenkorb/Kasse kommt bald...',
    
    // Bar Dashboard
    'bar.soundOn': 'Ton An',
    'bar.soundOff': 'Ton Aus',
    'bar.enableNotifications': 'Benachrichtigungen aktivieren',
    'bar.disableNotifications': 'Benachrichtigungen deaktivieren',
    'bar.start': 'Starten',
    'bar.ready': 'Fertig',
    'bar.readyForPickup': 'Bereit zur Abholung',
    'bar.unknownDrink': 'Unbekanntes Getränk',
    'bar.noDrinkOrders': 'Keine Getränkebestellungen',
    'bar.allCaughtUp': 'Alles erledigt! Derzeit keine ausstehenden Getränkebestellungen.',
    'bar.allDrinkOrders': 'Alle Getränkebestellungen',
    'bar.realTimeUpdates': 'Echtzeit-Updates',
    'bar.barMenu': 'Bar-Menü',
    'bar.viewAllBeverages': 'Alle Getränke anzeigen',
    
    // Errors and Messages
    'error.loadingFailed': 'Laden fehlgeschlagen',
    'error.tryAgain': 'Erneut versuchen',
    'error.accessDenied': 'Zugriff verweigert',
    'error.notFound': 'Nicht gefunden',
    'error.networkError': 'Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.',
    'error.seatsRange': 'Sitzplätze müssen zwischen 1 und 20 liegen',
    'error.tableNumberInvalid': 'Tischnummer muss größer als 0 sein',
    'error.menuLoadingError': 'Fehler beim Laden der Speisekarte',
    'error.ordersLoadingError': 'Fehler beim Laden der Bestellungen',
    'error.userNotFound': 'Benutzer nicht gefunden',
    'error.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten',
    'error.failedToLoad': 'Laden fehlgeschlagen',
    'error.noMenuItems': 'Derzeit sind keine Menüpunkte verfügbar.',
    'error.refreshMenu': 'Speisekarte aktualisieren',
    'error.addMenuItemsFirst': 'Bitte fügen Sie zuerst Menüpunkte hinzu.',
    'error.failedToCreate': 'Bestellung konnte nicht erstellt werden',
    'error.failedToAddItems': 'Artikel konnten nicht zur Bestellung hinzugefügt werden',
    'error.failedToUpdate': 'Bestellung konnte nicht aktualisiert werden',
    'success.orderCreated': 'Bestellung erfolgreich erstellt!',
    'success.orderUpdated': 'Bestellung erfolgreich aktualisiert!',
    'success.itemAdded': 'Artikel in den Warenkorb gelegt!',
    'success.menuItemCreated': 'Menüpunkt erfolgreich erstellt!',
    'success.menuItemUpdated': 'Menüpunkt erfolgreich aktualisiert!',
    'success.menuItemDeleted': 'Menüpunkt erfolgreich gelöscht',
    'success.tableUpdated': 'Tisch erfolgreich aktualisiert!',
    'success.chatCleared': 'Chat erfolgreich gelöscht',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('restaurant-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'de')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('restaurant-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}